// Tests server_context::reload_context: reinitializing a model's context
// (kv cache, slots, etc.) without reloading the model weights.
//
// Uses the qwen35-dense.gguf fixture generated by test-llama-archs, which is a
// valid GGUF with the correct Qwen3.5 architecture and deterministic random
// weights (n_vocab=128, n_ctx_train=128). The random weights are not a problem
// here: every assertion is a plumbing assertion (context size, decode success,
// logit equality across reloads), not a quality assertion.
//
// Run e.g.:
//   ./test-reload-context -m <path>/qwen35-dense.gguf -c 64 -np 1 -ngl 99
//
// Or against a real MTP model to exercise the speculative reinit branch:
//   ./test-reload-context -m <path>/Qwen3.5-9B-MTP-Q4_K_M.gguf \
//       --spec-type draft-mtp --spec-draft-n-max 2 -c 4096 -np 1 -ngl 99
#include "arg.h"
#include "common.h"
#include "llama.h"
#include <nlohmann/json.hpp>
#include "../tools/server/server-context.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "ggml.h"

// A tiny RAII stopwatch that prints elapsed ms to stderr on destruction.
struct scope_timer {
    const char * label;
    int64_t      t0;
    scope_timer(const char * l) : label(l), t0(ggml_time_ms()) {}
    ~scope_timer() {
        fprintf(stderr, "%s : %s took %lld ms\n", "main", label, (long long)(ggml_time_ms() - t0));
    }
};

// Print free/total memory for every GPU device. Useful for seeing KV cache
// allocation show up (or not) across reload_context calls.
static void log_gpu_memory(const char * when) {
    for (size_t i = 0; i < ggml_backend_dev_count(); ++i) {
        auto * dev = ggml_backend_dev_get(i);
        if (ggml_backend_dev_type(dev) != GGML_BACKEND_DEVICE_TYPE_GPU &&
            ggml_backend_dev_type(dev) != GGML_BACKEND_DEVICE_TYPE_IGPU) {
            continue;
        }
        size_t free_b = 0, total_b = 0;
        ggml_backend_dev_memory(dev, &free_b, &total_b);
        const size_t used_b = total_b - free_b;
        fprintf(stderr, "%s : GPU[%zu] %s: %zu MiB used / %zu MiB total (%s)\n",
                "main", i, ggml_backend_dev_name(dev),
                used_b / 1024 / 1024, total_b / 1024 / 1024, when);
    }
}

// Decode `tokens` on seq 0 with explicit positions; return logits of the last
// token, or nullptr on failure. Caller must NOT free the returned buffer (it is
// owned by the context and valid until the next decode).
static const float * decode_prompt(llama_context * ctx, const std::vector<llama_token> & tokens) {
    llama_batch batch = llama_batch_init((int) tokens.size(), 0, 1);
    for (size_t i = 0; i < tokens.size(); ++i) {
        common_batch_add(batch, tokens[i], (llama_pos) i, { 0 }, i + 1 == tokens.size());
    }
    const bool ok = llama_decode(ctx, batch) == 0;
    llama_batch_free(batch);
    if (!ok) {
        return nullptr;
    }
    return llama_get_logits_ith(ctx, (int32_t) tokens.size() - 1);
}

int main(int argc, char ** argv) {
    std::setlocale(LC_NUMERIC, "C");

    common_params params;
    common_init();

    if (!common_params_parse(argc, argv, params, LLAMA_EXAMPLE_SERVER)) {
        return 1;
    }

    // Avoid fit adjusting n_ctx / cache params under us, which would make the
    // before/after comparisons ambiguous. The caller is responsible for sizes.
    params.fit_params = false;

    // n_parallel == -1 (auto) is only resolved to a concrete value inside the
    // llama-server executable's main(), which we do not go through. Pin it
    // explicitly so setup_runtime_state() creates real slots.
    params.n_parallel = 1;

    ggml_backend_load_all();

    server_context ctx_server;

    // silence the state callback so it doesn't interfere with test output
    ctx_server.set_state_callback([](server_state, json) {});

    {
        scope_timer t("load model");
        if (!ctx_server.load_model(params)) {
            fprintf(stderr, "%s : failed to load model\n", __func__);
            return 1;
        }
    }
    

    llama_context * lctx = ctx_server.get_llama_context();
    if (lctx == nullptr) {
        fprintf(stderr, "%s : no context after load_model\n", __func__);
        return 1;
    }

    log_gpu_memory("after load_model");

    const llama_model * model = llama_get_model(lctx);
    const llama_vocab * vocab = llama_model_get_vocab(model);
    const int32_t       n_vocab = llama_vocab_n_tokens(vocab);

    // Use a small fixed prompt of valid token ids (fixture has n_vocab == 128).
    // We keep it identical across all decodes so logits are comparable.
    std::vector<llama_token> prompt = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };

    // capture logits from a fresh decode immediately after initial load
    const int32_t n_ctx_0 = (int32_t) llama_n_ctx(lctx);
    std::vector<float> logits_baseline;
    {
        scope_timer t("baseline decode");
        const float * lg = decode_prompt(lctx, prompt);
        if (lg == nullptr) {
            fprintf(stderr, "%s : baseline decode failed\n", __func__);
            return 1;
        }
        logits_baseline.assign(lg, lg + n_vocab);
    }

    // -------------------------------------------------------------------------
    // reload_context: grow the context window
    // -------------------------------------------------------------------------
    {
        common_params p2 = params;
        // grow the window; stay at or under n_ctx_train so setup_runtime_state
        // does not cap the slot size (the fixture has n_ctx_train == 128)
        p2.n_ctx = n_ctx_0 * 2;

        bool ok;
        {
            scope_timer t("reload_context (grow)");
            ok = ctx_server.reload_context(p2);
        }
        if (!ok) {
            fprintf(stderr, "%s : reload_context (grow) failed\n", __func__);
            return 1;
        }

        log_gpu_memory("after reload_context (grow)");

        llama_context * lctx2 = ctx_server.get_llama_context();
        const int32_t  n_ctx_2 = (int32_t) llama_n_ctx(lctx2);
        if (n_ctx_2 <= n_ctx_0) {
            fprintf(stderr, "%s : n_ctx did not grow: %d -> %d\n", __func__, n_ctx_0, n_ctx_2);
            return 1;
        }
        fprintf(stderr, "%s : n_ctx grew %d -> %d\n", __func__, n_ctx_0, n_ctx_2);

        // decode still works after reload
        const float * lg;
        {
            scope_timer t("decode (grow)");
            lg = decode_prompt(lctx2, prompt);
        }
        if (lg == nullptr) {
            fprintf(stderr, "%s : decode after reload_context (grow) failed\n", __func__);
            return 1;
        }

        // weights were not reloaded, so logits for the same fresh prompt must
        // match the baseline exactly (both contexts were warmed up + cleared,
        // then given an identical prompt on an empty kv cache)
        for (int32_t i = 0; i < n_vocab; ++i) {
            if (std::fabs(logits_baseline[i] - lg[i]) > 1e-5f) {
                fprintf(stderr, "%s : logits mismatch after grow at %d (%g != %g)\n",
                        __func__, i, (double) logits_baseline[i], (double) lg[i]);
                return 1;
            }
        }
        fprintf(stderr, "%s : logits match after grow\n", __func__);
    }

    // -------------------------------------------------------------------------
    // reload_context: shrink the context window back
    // -------------------------------------------------------------------------
    {
        common_params p3 = params; // restore original (smaller) n_ctx

        bool ok;
        {
            scope_timer t("reload_context (shrink)");
            ok = ctx_server.reload_context(p3);
        }
        if (!ok) {
            fprintf(stderr, "%s : reload_context (shrink) failed\n", __func__);
            return 1;
        }

        log_gpu_memory("after reload_context (shrink)");

        llama_context * lctx3 = ctx_server.get_llama_context();
        const int32_t  n_ctx_3 = (int32_t) llama_n_ctx(lctx3);
        if (n_ctx_3 != n_ctx_0) {
            fprintf(stderr, "%s : n_ctx did not restore: expected %d, got %d\n", __func__, n_ctx_0, n_ctx_3);
            return 1;
        }
        fprintf(stderr, "%s : n_ctx restored to %d\n", __func__, n_ctx_3);

        const float * lg;
        {
            scope_timer t("decode (shrink)");
            lg = decode_prompt(lctx3, prompt);
        }
        if (lg == nullptr) {
            fprintf(stderr, "%s : decode after reload_context (shrink) failed\n", __func__);
            return 1;
        }
        for (int32_t i = 0; i < n_vocab; ++i) {
            if (std::fabs(logits_baseline[i] - lg[i]) > 1e-5f) {
                fprintf(stderr, "%s : logits mismatch after shrink at %d (%g != %g)\n",
                        __func__, i, (double) logits_baseline[i], (double) lg[i]);
                return 1;
            }
        }
        fprintf(stderr, "%s : logits match after shrink\n", __func__);
    }

    // -------------------------------------------------------------------------
    // reload_context: change kv cache precision (smoke test)
    //
    // There is no public getter to read back the kv cache type from a live
    // context, so this only verifies that the reload with a different cache
    // type succeeds and decode still works. (catches the reinit_context path
    // being exercised with a non-default cache type.)
    // -------------------------------------------------------------------------
    {
        common_params p4 = params;
        p4.cache_type_k = GGML_TYPE_Q8_0;
        p4.cache_type_v = GGML_TYPE_Q8_0;

        bool ok;
        {
            scope_timer t("reload_context (q8_0)");
            ok = ctx_server.reload_context(p4);
        }
        if (!ok) {
            fprintf(stderr, "%s : reload_context (q8_0) failed\n", __func__);
            return 1;
        }

        log_gpu_memory("after reload_context (q8_0)");

        llama_context * lctx4 = ctx_server.get_llama_context();
        const float * lg;
        {
            scope_timer t("decode (q8_0)");
            lg = decode_prompt(lctx4, prompt);
        }
        if (lg == nullptr) {
            fprintf(stderr, "%s : decode after reload_context (q8_0) failed\n", __func__);
            return 1;
        }
        // q8_0 kv cache is lossy, so we do NOT compare logits to the f16
        // baseline; we only assert the decode succeeded.
        fprintf(stderr, "%s : q8_0 kv cache reload + decode ok\n", __func__);
    }

    fprintf(stderr, "%s : reload_context OK\n", __func__);
    return 0;
}
